#!/bin/sh
### bootstrap script ###############################

echo "Regenerating autotools files"
autoreconf --install --force --verbose || exit 1

echo "Now run ./configure, make, and make install."
